[package]
name = "deno-runtime-segfault"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_runtime = "0.132.0"
deno_core = "*"
tokio = { version = "1.33.0", features = ["full"] }
